Algoritmo "Crescente_Part1-EstruturaEnquanto"
// 

Var
   X,Y:Inteiro

Inicio
      Escreval("Digite dois numeros : ")
      Leia(x)
      Leia(Y)
      
      Enquanto X <> Y faca
        Se X < Y entao
           Escreval("Crescente ")
        Senao
             Escreval("Decrescente" )
        Fimse
      Escreval(" Escreva outros dois numeros : ")
      Leia(X)
      Leia(Y)

      Fimenquanto
      
      

Fimalgoritmo